

export const LOAD_UNICORNS_SUCCESS = "LOAD_UNICORNS_SUCCESS";
export const LOAD_HORNTYPES_SUCCES = "LOAD_HORNTYPES_SUCCES";
export const CREATE_UNICORN_SUCCESS = "CREATE_UNICORN_SUCCESS";
export const UPDATED_UNICORN_SUCCESS = "UPDATED_UNICORN_SUCCESS";
export const DELETE_UNICORN_SUCCESS = "DELETE_UNICORN_SUCCESS";

